In [13]:
from dynamic_array import DynamicArray

# Create an instance of DynamicArray with 4 columns
arr = DynamicArray(4)

# Add rows, delete rows, and check for timestamp existence

arr.updateRow(1, 1, 2.555)
arr.updateRow(1, 0, 1.0)
arr.updateRow(1, 2, 3.0)
arr.updateRow(1, 3, 4.0)
arr.updateRow(2, 0, 5.0)
arr.updateRow(2, 1, 6.0)
arr.updateRow(2, 2, 7.0)
arr.updateRow(2, 3, 8.0)
arr.updateRow(3, 0, 9.0)
arr.updateRow(3, 1, 10.0)
arr.updateRow(3, 2, 11.0)
arr.updateRow(3, 3, 12.0)
arr.updateRow(4, 0, 13.0)
arr.updateRow(4, 1, 14.0)
arr.updateRow(4, 2, 15.0)
arr.updateRow(4, 3, 16.0)
arr.updateRow(5, 0, 17.0)
arr.updateRow(5, 1, 18.0)
arr.updateRow(5, 2, 19.0)
arr.updateRow(5, 3, 20.0)
print(arr.timestampExists(1.0)) # Should print True
arr.print() # Use the C++ print method to display the array

True
1: 1 2.555 3 4 
2: 5 6 7 8 
3: 9 10 11 12 
4: 13 14 15 16 
5: 17 18 19 20 


In [14]:
print(type(arr.getTimestamps()))

<class 'list'>


In [15]:
print(arr.getLength())
print(arr.minKey())

5
1


In [16]:
arr.updateRow(1, 1, 444)
arr.print()


1: 1 444 3 4 
2: 5 6 7 8 
3: 9 10 11 12 
4: 13 14 15 16 
5: 17 18 19 20 


In [17]:
l = ["test1", "test2", "test3", "test4"]
print(l.index("test2"))

1


In [18]:
arr.getRow(4)

[13.0, 14.0, 15.0, 16.0]

In [21]:
import numpy as np
b  = arr.getSlice(5, 3)
ab = np.array(b)
print(ab.shape)
print(ab)

(3, 4)
[[ 9. 10. 11. 12.]
 [13. 14. 15. 16.]
 [17. 18. 19. 20.]]


In [ ]:
ab[0,1]